import { Roboto } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/shared/Navbar";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "My NextJs app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar />
        <div className="min-h-screen">{children}</div>
        <footer className="text-center text-xl bg-blue-300 py-2">This is footer</footer>
      </body>
    </html>
  );
}
